"""
Goal Generator — Internal drives and intention generation.

The agent's ability to generate its own goals (not just respond to prompts).
Driven by three core drives:
- Curiosity: investigate anomalies and unknowns
- Maintenance: check system health and consistency
- Evolution: improve skills, memory, and processes
"""

from __future__ import annotations

import json
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Optional


class Drive(Enum):
    CURIOSITY = "curiosity"       # Investigate anomalies, explore unknowns
    MAINTENANCE = "maintenance"   # Check health, verify consistency, clean up
    EVOLUTION = "evolution"       # Self-improve, optimize, learn


class GoalPriority(Enum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


class Goal:
    """A single goal with drive source, priority, and status."""

    def __init__(
        self,
        description: str,
        drive: Drive,
        priority: GoalPriority = GoalPriority.MEDIUM,
        source: str = "internal",
        metadata: Optional[dict] = None,
    ):
        self.id = f"{drive.value}_{datetime.now().strftime('%Y%m%d%H%M%S%f')}"
        self.description = description
        self.drive = drive
        self.priority = priority
        self.source = source  # "internal" or "user"
        self.status = "active"  # active | completed | cancelled | expired
        self.created_at = datetime.now().isoformat()
        self.metadata = metadata or {}
        self.meta_score: float = 0.0  # MetaCognition-adjusted score (0-1)

    def compute_meta_score(self, confidence: float, calibration: float) -> float:
        """
        Adjust goal priority based on MetaCognition confidence and calibration.

        High confidence + high calibration = trust the goal (boost).
        Low confidence = be cautious (reduce).
        High confidence + low calibration = overconfident (penalize).

        Returns the computed score (0-1).
        """
        # Base: priority value normalized (1-4 → 0.25-1.0)
        base = self.priority.value / 4.0

        # Confidence factor: higher confidence → more trust in goal
        conf_factor = 0.5 + 0.5 * confidence  # range 0.5-1.0

        # Calibration penalty: overconfident → reduce
        # calibration = accuracy / confidence; <1 means overconfident
        cal_penalty = max(0.0, 1.0 - (1.0 - calibration) * 0.5)

        self.meta_score = min(1.0, base * conf_factor * cal_penalty)
        return self.meta_score

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "description": self.description,
            "drive": self.drive.value,
            "priority": self.priority.value,
            "source": self.source,
            "status": self.status,
            "created_at": self.created_at,
            "metadata": self.metadata,
            "meta_score": self.meta_score,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Goal":
        goal = cls(
            description=data["description"],
            drive=Drive(data["drive"]),
            priority=GoalPriority(data.get("priority", 2)),
            source=data.get("source", "internal"),
            metadata=data.get("metadata", {}),
        )
        goal.id = data.get("id", goal.id)
        goal.status = data.get("status", "active")
        goal.created_at = data.get("created_at", goal.created_at)
        goal.meta_score = data.get("meta_score", 0.0)
        return goal


class GoalGenerator:
    """
    Generates and manages internal goals based on drives.
    
    Goal lifecycle:
    1. Generated by a drive (curiosity, maintenance, evolution)
    2. Scored by: urgency × relevance × drive_strength
    3. Added to the active goals queue (max 10)
    4. Processed during inner monologue reflections
    5. Completed, cancelled, or expired (after 24h without progress)
    """

    MAX_ACTIVE_GOALS = 10

    def __init__(
        self,
        storage_path: Path,
        drive_strengths: Optional[dict[Drive, float]] = None,
    ):
        self.path = storage_path / "goals.json"
        self.path.parent.mkdir(parents=True, exist_ok=True)

        # Drive strengths (0-1, how strongly each drive generates goals)
        self.drives = drive_strengths or {
            Drive.CURIOSITY: 0.7,
            Drive.MAINTENANCE: 0.8,
            Drive.EVOLUTION: 0.5,
        }

        self._goals: list[Goal] = self._load()

    def _load(self) -> list[Goal]:
        if self.path.exists():
            try:
                data = json.loads(self.path.read_text())
                return [Goal.from_dict(g) for g in data]
            except (json.JSONDecodeError, KeyError):
                pass
        return []

    def _save(self) -> None:
        data = [g.to_dict() for g in self._goals]
        self.path.write_text(json.dumps(data, indent=2, ensure_ascii=False))

    # --- Goal Generation from Drives ---

    def generate_from_curiosity(self, anomaly: str, context: str = "") -> Optional[Goal]:
        """
        Generate a curiosity-driven goal from an anomaly.
        
        Only creates the goal if the curiosity drive is strong enough
        and the anomaly seems worth investigating.
        """
        strength = self.drives.get(Drive.CURIOSITY, 0.5)
        if strength < 0.3:
            return None  # Drive too weak

        goal = Goal(
            description=f"Investigate: {anomaly}",
            drive=Drive.CURIOSITY,
            priority=GoalPriority.MEDIUM,
            source="internal",
            metadata={"anomaly": anomaly, "context": context},
        )
        self._add_goal(goal)
        return goal

    def generate_from_maintenance(self, check_type: str, target: str) -> Optional[Goal]:
        """
        Generate a maintenance-driven goal.
        
        Examples: "check system health", "verify data consistency", "prune stale entries"
        """
        strength = self.drives.get(Drive.MAINTENANCE, 0.5)
        if strength < 0.3:
            return None

        goal = Goal(
            description=f"Maintenance: {check_type} — {target}",
            drive=Drive.MAINTENANCE,
            priority=GoalPriority.HIGH,  # Maintenance is usually high priority
            source="internal",
            metadata={"check_type": check_type, "target": target},
        )
        self._add_goal(goal)
        return goal

    def generate_from_evolution(self, improvement: str, target: str = "") -> Optional[Goal]:
        """
        Generate an evolution-driven goal.
        
        Examples: "update skill X", "optimize process Y", "learn from failure Z"
        """
        strength = self.drives.get(Drive.EVOLUTION, 0.5)
        if strength < 0.3:
            return None

        goal = Goal(
            description=f"Evolve: {improvement}" + (f" — {target}" if target else ""),
            drive=Drive.EVOLUTION,
            priority=GoalPriority.LOW,  # Evolution is important but not urgent
            source="internal",
            metadata={"improvement": improvement, "target": target},
        )
        self._add_goal(goal)
        return goal

    def add_user_goal(self, description: str, priority: GoalPriority = GoalPriority.HIGH) -> Goal:
        """Add a goal explicitly requested by the user."""
        goal = Goal(
            description=description,
            drive=Drive.CURIOSITY,  # User goals default to curiosity drive
            priority=priority,
            source="user",
        )
        self._add_goal(goal)
        return goal

    def _add_goal(self, goal: Goal) -> None:
        """Add a goal to the queue, respecting the max limit."""
        # Check for duplicates
        for existing in self._goals:
            if existing.status == "active" and existing.description == goal.description:
                return  # Already exists

        self._goals.append(goal)

        # Enforce max active goals — expire lowest priority if over limit
        active = [g for g in self._goals if g.status == "active"]
        if len(active) > self.MAX_ACTIVE_GOALS:
            # Sort by (priority ascending, then oldest first)
            active.sort(key=lambda g: (g.priority.value, g.created_at))
            to_expire = len(active) - self.MAX_ACTIVE_GOALS
            for i in range(to_expire):
                active[i].status = "expired"

        self._save()

    # --- Goal Management ---

    def complete_goal(self, goal_id: str) -> bool:
        """Mark a goal as completed."""
        for g in self._goals:
            if g.id == goal_id:
                g.status = "completed"
                self._save()
                return True
        return False

    def cancel_goal(self, goal_id: str) -> bool:
        """Cancel a goal."""
        for g in self._goals:
            if g.id == goal_id:
                g.status = "cancelled"
                self._save()
                return True
        return False

    def active_goals(self, max_count: int = 5, sort_by_meta: bool = False) -> list[Goal]:
        """Get active goals sorted by priority (or meta_score if sort_by_meta)."""
        active = [g for g in self._goals if g.status == "active"]
        if sort_by_meta and any(g.meta_score > 0 for g in active):
            active.sort(key=lambda g: g.meta_score, reverse=True)
        else:
            active.sort(key=lambda g: g.priority.value, reverse=True)
        return active[:max_count]

    def score_all_goals(self, confidence: float, calibration: float) -> None:
        """
        Apply MetaCognition confidence/calibration to all active goals.
        Updates each goal's meta_score in place.
        """
        for g in self._goals:
            if g.status == "active":
                g.compute_meta_score(confidence, calibration)
        self._save()

    def expire_stale(self, max_age_hours: int = 24) -> int:
        """Expire goals that haven't progressed in a while."""
        from datetime import timedelta
        cutoff = datetime.now() - timedelta(hours=max_age_hours)
        expired = 0
        for g in self._goals:
            if g.status != "active":
                continue
            try:
                created = datetime.fromisoformat(g.created_at)
                if created < cutoff:
                    g.status = "expired"
                    expired += 1
            except (ValueError, TypeError):
                pass
        if expired > 0:
            self._save()
        return expired

    # --- Summary ---

    def summary(self, max_count: int = 3) -> str:
        """Compact summary for context injection."""
        active = self.active_goals(max_count)
        if not active:
            return "No active internal goals."

        parts = []
        for g in active:
            emoji = {"curiosity": "🔮", "maintenance": "🔧", "evolution": "🧬"}.get(g.drive.value, "→")
            parts.append(f"{emoji} {g.description}")

        return " | ".join(parts)

    def to_dict(self) -> list[dict]:
        return [g.to_dict() for g in self._goals]

    def status(self) -> dict:
        active = [g for g in self._goals if g.status == "active"]
        return {
            "total_goals": len(self._goals),
            "active_goals": len(active),
            "drive_strengths": {d.value: s for d, s in self.drives.items()},
            "path": str(self.path),
        }
